import { useEffect, useState, type FormEvent } from 'react';
import { AdminShell } from './AdminPagesV2';
import { ApiError, api } from '../services/api';
import { EmptyState, ErrorState, LoadingState } from '../components/States';
import { showToast } from '../components/ToastHost';

type Complaint = { id: number; entryNumber: string; type: 'RECLAMO' | 'QUEJA'; status: 'PENDIENTE' | 'RESPONDIDO' | 'CERRADO'; consumerName: string; consumerEmail: string; consumerPhone?: string | null; consumerAddress?: string | null; orderNumber?: string | null; productServiceDescription: string; detail: string; consumerRequest: string; response?: string | null; createdAt: string };
type Page<T> = { content: T[]; totalPages: number; totalElements: number; number: number };
const statusLabel: Record<Complaint['status'], string> = { PENDIENTE: 'Pendiente', RESPONDIDO: 'Respondido', CERRADO: 'Cerrado' };
const typeLabel: Record<Complaint['type'], string> = { RECLAMO: 'Reclamo', QUEJA: 'Queja' };
const message = (reason: unknown, fallback: string) => reason instanceof ApiError ? reason.message : fallback;
const date = (value: string) => new Intl.DateTimeFormat('es-PE', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));

export function AdminComplaintsPage() {
  const [rows, setRows] = useState<Complaint[]>([]); const [page, setPage] = useState(0); const [totalPages, setTotalPages] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [selected, setSelected] = useState<Complaint | null>(null);
  async function load() { setLoading(true); setError(''); try { const result = await api.get<Page<Complaint>>('/complaints', { auth: 'staff', query: { page, size: 20, sort: 'createdAt,desc' } }); setRows(result.content || []); setTotalPages(result.totalPages || 0); } catch (reason) { setError(message(reason, 'No se pudo cargar el Libro de Reclamaciones.')); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [page]);
  return <AdminShell title="Libro de Reclamaciones" description="Consulta y responde las atenciones registradas por tus clientes." activePage="/admin/reclamos"><section className="table-card react-pos-table"><div className="card-header"><div><span className="field-hint">ATENCIÓN AL CLIENTE</span><h2>Hojas registradas</h2></div><a className="btn btn-secondary btn-sm" href="/libro-reclamaciones" target="_blank" rel="noreferrer">Ver formulario público</a></div>{error ? <ErrorState message={error} /> : loading ? <LoadingState label="Cargando hojas…" /> : rows.length ? <div className="table-scroll"><table className="data-table"><thead><tr><th>Código</th><th>Tipo</th><th>Consumidor</th><th>Fecha</th><th>Estado</th><th /></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td data-label="Código" className="table-cell-primary">{row.entryNumber}</td><td data-label="Tipo">{typeLabel[row.type]}</td><td data-label="Consumidor">{row.consumerName}</td><td data-label="Fecha">{date(row.createdAt)}</td><td data-label="Estado"><span className={`badge ${row.status === 'PENDIENTE' ? 'badge-warning' : row.status === 'CERRADO' ? 'badge-neutral' : 'badge-success'}`}>{statusLabel[row.status]}</span></td><td data-label="Acciones"><button className="btn btn-secondary btn-sm" type="button" onClick={() => setSelected(row)}>Ver detalle</button></td></tr>)}</tbody></table></div> : <EmptyState>Por ahora no hay hojas registradas.</EmptyState>}{totalPages > 0 && <div className="pagination-bar"><button className="btn btn-secondary btn-sm" disabled={page === 0} type="button" onClick={() => setPage((value) => value - 1)}>Anterior</button><span>Página {page + 1} de {totalPages}</span><button className="btn btn-secondary btn-sm" disabled={page + 1 >= totalPages} type="button" onClick={() => setPage((value) => value + 1)}>Siguiente</button></div>}</section>{selected && <ComplaintDetail complaint={selected} onClose={() => setSelected(null)} onSaved={() => { setSelected(null); void load(); }} />}</AdminShell>;
}

function ComplaintDetail({ complaint, onClose, onSaved }: { complaint: Complaint; onClose: () => void; onSaved: () => void }) {
  const [response, setResponse] = useState(complaint.response || ''); const [close, setClose] = useState(complaint.status === 'CERRADO'); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (complaint.status === 'CERRADO') return; if (response.trim().length < 5) { setError('Escribe una respuesta clara de al menos 5 caracteres.'); return; } setSaving(true); setError(''); try { await api.patch(`/complaints/${complaint.id}/response`, { response: response.trim(), close }, { auth: 'staff' }); showToast(close ? 'Hoja respondida y cerrada.' : 'Respuesta guardada correctamente.'); onSaved(); } catch (reason) { setError(message(reason, 'No se pudo guardar la respuesta.')); } finally { setSaving(false); } }
  return <div className="react-dialog-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="react-dialog react-complaint-dialog" role="dialog" aria-modal="true" aria-labelledby="complaint-detail-title"><div className="react-dialog-header"><div><span className="field-hint">{typeLabel[complaint.type]} · {complaint.entryNumber}</span><h2 id="complaint-detail-title">Detalle de atención</h2><p className="field-hint">Registrado el {date(complaint.createdAt)}</p></div><button className="btn btn-ghost" type="button" aria-label="Cerrar" onClick={onClose}>×</button></div>{error && <div className="alert alert-danger" role="alert">{error}</div>}<div className="react-complaint-detail"><div className="react-complaint-detail-grid"><p><strong>Consumidor</strong><span>{complaint.consumerName}</span></p><p><strong>Contacto</strong><span>{complaint.consumerEmail}{complaint.consumerPhone ? ` · ${complaint.consumerPhone}` : ''}</span></p><p><strong>Domicilio</strong><span>{complaint.consumerAddress || 'No registrado'}</span></p><p><strong>Producto o servicio</strong><span>{complaint.productServiceDescription}</span></p><p><strong>Pedido</strong><span>{complaint.orderNumber || 'No indicado'}</span></p></div><div className="react-complaint-copy"><strong>Detalle</strong><p>{complaint.detail}</p><strong>Pedido del consumidor</strong><p>{complaint.consumerRequest}</p></div>{complaint.status === 'CERRADO' ? <div className="react-complaint-copy"><strong>Respuesta registrada</strong><p>{complaint.response || 'Sin respuesta detallada.'}</p></div> : <form onSubmit={submit}><label className="field"><span className="field-label">Respuesta al consumidor</span><textarea className="input" required maxLength={5000} rows={5} value={response} onChange={(event) => setResponse(event.target.value)} placeholder="Explica la solución o las acciones adoptadas." /></label><label className="checkbox-field"><input type="checkbox" checked={close} onChange={(event) => setClose(event.target.checked)} />Marcar como atendida y cerrada</label><div className="react-dialog-actions"><button className="btn btn-secondary" type="button" onClick={onClose}>Cancelar</button><button className="btn btn-primary" disabled={saving}>{saving ? 'Guardando…' : 'Guardar respuesta'}</button></div></form>}</div></section></div>;
}
