import { useEffect, useState, type FormEvent } from 'react';
import { AdminShell } from './AdminPagesV2';
import { ApiError, api, getStaffSession } from '../services/api';
import { EmptyState, ErrorState, LoadingState } from '../components/States';
import { showToast } from '../components/ToastHost';
import { contactPhoneInput, digitsOnly, firstError, validateContactPhone, validateDni, validateEmail, validatePersonName, validateRuc } from '../services/validation';

type DocType = 'SIN_DOCUMENTO' | 'DNI' | 'RUC' | 'CE';
type Status = 'ACTIVE' | 'INACTIVE';
type Customer = { id: number; fullName: string; docType: DocType; docNumber?: string | null; phone?: string | null; email?: string | null; status: Status; createdAt: string };
type CustomerPage = { content: Customer[]; totalPages: number; totalElements: number; number: number };
const docLabels: Record<DocType, string> = { SIN_DOCUMENTO: 'Sin documento', DNI: 'DNI', RUC: 'RUC', CE: 'Carné de extranjería' };
const statusLabels: Record<Status, string> = { ACTIVE: 'Activo', INACTIVE: 'Inactivo' };
const errorMessage = (reason: unknown, fallback: string) => reason instanceof ApiError ? reason.message : fallback;
const formatDate = (value: string) => new Intl.DateTimeFormat('es-PE', { dateStyle: 'medium' }).format(new Date(value));

export function AdminCustomersPage() {
  const [rows, setRows] = useState<Customer[]>([]); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [page, setPage] = useState(0); const [totalPages, setTotalPages] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [editing, setEditing] = useState<Customer | null | undefined>(undefined);
  const canCreate = getStaffSession()?.user.permissions.includes('CLIENTES_CREAR') ?? false; const canEdit = getStaffSession()?.user.permissions.includes('CLIENTES_EDITAR') ?? false;
  async function load() { setLoading(true); setError(''); try { const result = await api.get<CustomerPage>('/customers', { auth: 'staff', query: { search: search.trim() || undefined, status: status || undefined, page, size: 20, sort: 'fullName,asc' } }); setRows(result.content || []); setTotalPages(result.totalPages || 0); } catch (reason) { setError(errorMessage(reason, 'No se pudieron cargar los clientes.')); } finally { setLoading(false); } }
  useEffect(() => { const timer = window.setTimeout(() => void load(), 250); return () => window.clearTimeout(timer); }, [search, status, page]);
  function updateSearch(value: string) { setSearch(value); setPage(0); }
  async function toggle(customer: Customer) { if (!canEdit) return; try { const next = await api.patch<Customer>(`/customers/${customer.id}/status`, { status: customer.status === 'ACTIVE' ? 'INACTIVE' : 'ACTIVE' }, { auth: 'staff' }); setRows((current) => current.map((item) => item.id === next.id ? next : item)); showToast(`Cliente ${next.status === 'ACTIVE' ? 'activado' : 'desactivado'} correctamente.`); } catch (reason) { showToast(errorMessage(reason, 'No se pudo actualizar el estado.'), 'Error', 'error'); } }
  return <AdminShell title="Clientes" description="DNI y correo son opcionales. El documento, si se indica, debe ser único." activePage="/admin/clientes"><div className="page-actions react-customers-actions">{canCreate && <button className="btn btn-primary" type="button" onClick={() => setEditing(null)}>+ Nuevo cliente</button>}</div><section className="filter-bar react-customers-filter"><label className="topbar-search"><span aria-hidden="true">⌕</span><input type="search" placeholder="Buscar por nombre, documento o teléfono…" aria-label="Buscar clientes" value={search} onChange={(event) => updateSearch(event.target.value)} /></label><select className="select" aria-label="Filtrar por estado" value={status} onChange={(event) => { setStatus(event.target.value); setPage(0); }}><option value="">Todos los estados</option><option value="ACTIVE">Activo</option><option value="INACTIVE">Inactivo</option></select></section><section className="table-card react-customers-table">{error ? <ErrorState message={error} /> : loading ? <LoadingState label="Cargando clientes…" /> : rows.length ? <div className="table-scroll"><table className="data-table"><thead><tr><th>Cliente</th><th>Documento</th><th>Teléfono</th><th>Email</th><th>Estado</th><th /></tr></thead><tbody>{rows.map((customer) => <tr key={customer.id}><td data-label="Cliente" className="table-cell-primary">{customer.fullName}<small className="table-cell-secondary">Registrado {formatDate(customer.createdAt)}</small></td><td data-label="Documento" className="mono">{customer.docNumber ? `${docLabels[customer.docType]} ${customer.docNumber}` : '—'}</td><td data-label="Teléfono">{customer.phone || '—'}</td><td data-label="Email">{customer.email || '—'}</td><td data-label="Estado"><span className={`badge ${customer.status === 'ACTIVE' ? 'badge-success' : 'badge-neutral'}`}>{statusLabels[customer.status]}</span></td><td data-label="Acciones"><div className="table-actions">{canEdit && <><button className="btn btn-ghost btn-sm" type="button" onClick={() => setEditing(customer)}>Editar</button><button className="btn btn-ghost btn-sm" type="button" onClick={() => void toggle(customer)}>{customer.status === 'ACTIVE' ? 'Desactivar' : 'Activar'}</button></>}</div></td></tr>)}</tbody></table></div> : <EmptyState>No se encontraron clientes.</EmptyState>}{totalPages > 0 && <div className="pagination-bar"><button className="btn btn-secondary btn-sm" disabled={page === 0} onClick={() => setPage((value) => value - 1)}>Anterior</button><span>Página {page + 1} de {totalPages}</span><button className="btn btn-secondary btn-sm" disabled={page + 1 >= totalPages} onClick={() => setPage((value) => value + 1)}>Siguiente</button></div>}</section>{editing !== undefined && <CustomerDialog customer={editing} onClose={() => setEditing(undefined)} onSaved={() => { setEditing(undefined); void load(); }} />}</AdminShell>;
}

function CustomerDialog({ customer, onClose, onSaved }: { customer: Customer | null; onClose: () => void; onSaved: () => void }) {
  const [fullName, setFullName] = useState(customer?.fullName || ''); const [docType, setDocType] = useState<DocType>(customer?.docType || 'SIN_DOCUMENTO'); const [docNumber, setDocNumber] = useState(customer?.docNumber || ''); const [phone, setPhone] = useState(customer?.phone || ''); const [email, setEmail] = useState(customer?.email || ''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  function changeDocType(value: DocType) { setDocType(value); setDocNumber(value === 'DNI' ? digitsOnly(docNumber, 8) : value === 'RUC' ? digitsOnly(docNumber, 11) : value === 'SIN_DOCUMENTO' ? '' : docNumber.slice(0, 15)); }
  function changeDocNumber(value: string) { setDocNumber(docType === 'DNI' || docType === 'RUC' ? digitsOnly(value, docType === 'DNI' ? 8 : 11) : docType === 'CE' ? value.replace(/[^a-zA-Z0-9]/g, '').slice(0, 15) : ''); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const validation = firstError(validatePersonName(fullName, 'el nombre completo', 150), docType === 'DNI' ? validateDni(docNumber) : docType === 'RUC' ? validateRuc(docNumber, true) : null, validateContactPhone(phone), validateEmail(email)); if (validation) { setError(validation); return; } setSaving(true); setError(''); try { const payload = { fullName: fullName.trim(), docType, docNumber: docNumber.trim() || null, phone: phone.trim() || null, email: email.trim() || null, birthDate: null }; if (customer) await api.put(`/customers/${customer.id}`, payload, { auth: 'staff' }); else await api.post('/customers', payload, { auth: 'staff' }); showToast(customer ? 'Cliente actualizado correctamente.' : 'Cliente creado correctamente.'); onSaved(); } catch (reason) { setError(errorMessage(reason, 'No se pudo guardar el cliente.')); } finally { setSaving(false); } }
  return <div className="react-dialog-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="react-dialog" role="dialog" aria-modal="true" aria-labelledby="customer-dialog-title"><div className="react-dialog-header"><div><span className="field-hint">CLIENTES</span><h2 id="customer-dialog-title">{customer ? 'Editar cliente' : 'Nuevo cliente'}</h2></div><button className="btn btn-ghost" type="button" aria-label="Cerrar" onClick={onClose}>×</button></div>{error && <div className="alert alert-danger" role="alert">{error}</div>}<form className="form-grid" onSubmit={submit} noValidate><label className="field field-span-2"><span className="field-label">Nombre completo</span><input className="input" required maxLength={150} value={fullName} onChange={(event) => setFullName(event.target.value)} /></label><label className="field"><span className="field-label">Tipo de documento</span><select className="select" value={docType} onChange={(event) => changeDocType(event.target.value as DocType)}>{Object.entries(docLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label className="field"><span className="field-label">Número de documento</span><input className="input" inputMode={docType === 'CE' ? 'text' : 'numeric'} maxLength={docType === 'DNI' ? 8 : docType === 'RUC' ? 11 : 15} value={docNumber} disabled={docType === 'SIN_DOCUMENTO'} onChange={(event) => changeDocNumber(event.target.value)} /></label><label className="field"><span className="field-label">Teléfono</span><input className="input" inputMode="tel" maxLength={20} value={phone} onChange={(event) => setPhone(contactPhoneInput(event.target.value))} /></label><label className="field"><span className="field-label">Email</span><input className="input" type="email" maxLength={120} value={email} onChange={(event) => setEmail(event.target.value.replace(/\s/g, '').slice(0, 120))} /></label><div className="react-dialog-actions"><button className="btn btn-secondary" type="button" onClick={onClose}>Cancelar</button><button className="btn btn-primary" disabled={saving}>{saving ? 'Guardando…' : customer ? 'Guardar cambios' : 'Crear cliente'}</button></div></form></section></div>;
}
