import { FormEvent, useEffect, useState } from 'react';
import { ApiError, api, clearStaffSession, getStaffSession, setStaffSession } from '../services/api';
import { ErrorState, LoadingState } from '../components/States';

const modules = [{ path: '/admin/dashboard', label: 'Dashboard' }, { path: '/admin/productos', label: 'Productos' }, { path: '/admin/catalogo', label: 'Catálogo' }, { path: '/admin/inventario', label: 'Inventario' }, { path: '/admin/pos', label: 'Punto de venta' }, { path: '/admin/pedidos', label: 'Pedidos' }, { path: '/admin/clientes', label: 'Clientes' }, { path: '/admin/reportes', label: 'Reportes' }, { path: '/admin/configuracion', label: 'Configuración' }, { path: '/admin/usuarios', label: 'Usuarios' }];

export function AdminLoginPage() { const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(''); try { const data = await api.post<{ accessToken: string; refreshToken: string; user: { id: number; username: string; fullName: string; permissions: string[]; mustChangePassword?: boolean } }>('/auth/login', { username, password }); setStaffSession(data); window.history.pushState({}, '', data.user.mustChangePassword ? '/admin/cambiar-contrasena' : '/admin/dashboard'); window.dispatchEvent(new PopStateEvent('popstate')); } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'No se pudo iniciar sesión'); } finally { setLoading(false); } } return <main className="admin-login"><div className="admin-login-card"><span className="store-kicker">QYNEX · GESTIÓN</span><h1>Iniciar sesión</h1><p>Accede al panel de tu empresa.</p><form onSubmit={submit}><label>Usuario<input className="input" required value={username} onChange={(event) => setUsername(event.target.value)} /></label><label>Contraseña<input className="input" required type="password" value={password} onChange={(event) => setPassword(event.target.value)} /></label>{error && <div className="alert alert-danger" role="alert">{error}</div>}<button className="btn btn-primary" disabled={loading}>{loading ? 'Ingresando…' : 'Ingresar'}</button></form></div></main>; }

function AdminShell({ children, title }: { children: React.ReactNode; title: string }) { const session = getStaffSession(); return <div className="admin-app"><aside className="admin-sidebar"><a className="admin-brand" href="/admin/dashboard">Qynex</a><nav aria-label="Menú de administración">{modules.map((module) => <a className={window.location.pathname === module.path ? 'is-active' : ''} href={module.path} key={module.path}>{module.label}</a>)}</nav><button className="btn btn-secondary" onClick={() => { clearStaffSession(); window.history.pushState({}, '', '/admin/login'); window.dispatchEvent(new PopStateEvent('popstate')); }}>Cerrar sesión</button></aside><main className="admin-content"><header className="admin-topbar"><span>{session?.user.fullName || 'Administrador'}</span><span>{session?.user.username}</span></header><div className="admin-page-heading"><span className="store-kicker">PANEL DE CONTROL</span><h1>{title}</h1></div>{children}</main></div>; }

export function AdminDashboardPage() { const [data, setData] = useState<Record<string, unknown> | null>(null); const [error, setError] = useState(''); useEffect(() => { api.get<Record<string, unknown>>('/reports/dashboard', { auth: 'staff' }).then(setData).catch((reason) => setError(reason.message)); }, []); return <AdminShell title="Resumen del negocio">{error ? <ErrorState message={error} /> : !data ? <LoadingState label="Cargando indicadores…" /> : <div className="admin-dashboard-grid">{Object.entries(data).slice(0, 8).map(([key, value]) => <article className="admin-metric" key={key}><span>{key.replaceAll('_', ' ')}</span><strong>{typeof value === 'object' ? JSON.stringify(value) : String(value)}</strong></article>)}</div>}</AdminShell>; }

export function AdminModulePage({ title }: { title: string }) { return <AdminShell title={title}><section className="admin-migration-note"><h2>Ruta administrativa no disponible</h2><p>Esta ruta no corresponde a un módulo activo del panel. Regresa al dashboard para continuar.</p><a className="btn btn-primary" href="/admin/dashboard">Volver al dashboard</a></section></AdminShell>; }
